In [ ]:
print("Hello")

Hello


In [ ]:
import numpy as np
arr=np.array([1,2,3,6,4,5])
ans=arr[::-1]
print(ans)

[5 4 6 3 2 1]


In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[1,2],[3,4]])
arr1==arr2

array([[ True,  True],
       [ True,  True]])

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3,])
array,counts=np.unique(x,return_counts=True)
mfe1=array[np.argmax(counts)]
list1=[]
for i in range(len(x)):
  if(x[i]==mfe1):
    list1.append(i)
print(f"mfe1: {mfe1}, indeces:{list1}")
array,counts=np.unique(y,return_counts=True)
mfe2=array[np.argmax(counts)]
list2=[]
for i in range(len(y)):
  if(x[i]==mfe2):
    list2.append(i)
print(f"mfe2: {mfe2}, indeces:{list2}")

mfe1: 1, indeces:[0, 5, 7, 8, 9]
mfe2: 1, indeces:[0, 5, 7, 8, 9]


In [ ]:
import numpy as np
gfg=np.matrix('[4,1,9;12,3,1;4,5,6]')
print(gfg.sum())
print(gfg.sum(axis=0))
print(gfg.sum(axis=1))


45
[[20  9 16]]
[[14]
 [16]
 [15]]
